services:
  mailpit:
      image: axllent/mailpit:latest
      container_name: mailpit
      restart: unless-stopped
      ports:
        - "1025:1025"
        - "8025:8025"
      environment:
        MP_MAX_MESSAGES: 100
      healthcheck:
        test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025/"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
        
  stockquotealert:
    build:
      context: ./StockQuoteAlert
    container_name: stockquotealert
    environment:
      SMTP_HOST: mailpit
    restart: unless-stopped
    depends_on:
      mailpit:
        condition: service_healthy

  tests:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    profiles:
      - test
    working_dir: /src
    volumes:
      - .:/src
    command: ["dotnet", "test", "StockQuoteAlert.Tests/StockQuoteAlert.Tests.csproj"]